name: on push to main
on:
  push:
    branches:
      - main
jobs:
  deploy:
    
    permissions: 
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: ${{ github.actor }}
      
      - name: Install Node.js for backend
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend
      - working-directory: backend  
        run: npm install
      - uses: alonch/actions-aws-backend-setup@main
        with: 
          instance: redirect-qr
      - uses: alonch/actions-aws-function-node@main
        id: backend
        with: 
          name: backend
          artifacts: backend
          entrypoint-file: src/app.js
          entrypoint-function: handler
          allow-public-access: true
          memory: 1536